/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import javax.swing.*;
import java.awt.*;
/**
 *
 * @author mamia
 */
public class FrmVenta extends javax.swing.JFrame {

    JLabel titulo;
    JLabel lblId, lblFecha, lblTotal;
    JLabel lblMetodo, lblCliente, lblUsuario;

    JTextField txtId, txtFecha, txtTotal;
    JTextField txtMetodo, txtCliente, txtUsuario;

    JButton btnAgregar, btnActualizar, btnEliminar;
    /**
     * Creates new form FrmVenta
     */
    public FrmVenta() {
        initComponents();
          setTitle("CRUD VENTAS");
        setSize(500, 550);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLayout(null);
        setLocationRelativeTo(null);

        // FONDO
        getContentPane().setBackground(new Color(25, 25, 40));

        // TITULO
        titulo = new JLabel("GESTIÓN DE VENTAS");
        titulo.setBounds(90, 20, 320, 40);
        titulo.setFont(new Font("Arial", Font.BOLD, 24));
        titulo.setForeground(new Color(0, 255, 200));

        // LABELS
        lblId = new JLabel("ID Venta:");
        lblFecha = new JLabel("Fecha:");
        lblTotal = new JLabel("Total Venta:");
        lblMetodo = new JLabel("Método Pago:");
        lblCliente = new JLabel("ID Cliente:");
        lblUsuario = new JLabel("ID Usuario:");

        JLabel[] labels = {
            lblId, lblFecha, lblTotal,
            lblMetodo, lblCliente, lblUsuario
        };

        for (JLabel lbl : labels) {

            lbl.setForeground(Color.WHITE);
            lbl.setFont(new Font("Segoe UI", Font.BOLD, 14));

        }

        // TEXTFIELDS
        txtId = new JTextField();
        txtFecha = new JTextField();
        txtTotal = new JTextField();
        txtMetodo = new JTextField();
        txtCliente = new JTextField();
        txtUsuario = new JTextField();

        JTextField[] campos = {
            txtId, txtFecha, txtTotal,
            txtMetodo, txtCliente, txtUsuario
        };

        for (JTextField txt : campos) {

            txt.setBackground(new Color(40, 40, 60));
            txt.setForeground(Color.WHITE);
            txt.setCaretColor(Color.WHITE);

            txt.setBorder(
                    BorderFactory.createLineBorder(
                            new Color(0, 255, 200), 2));

            txt.setFont(new Font("Segoe UI", Font.PLAIN, 14));

        }

        // BOTONES
        btnAgregar = new JButton("Agregar");
        btnActualizar = new JButton("Actualizar");
        btnEliminar = new JButton("Eliminar");

        JButton[] botones = {
            btnAgregar, btnActualizar, btnEliminar
        };

        for (JButton btn : botones) {

            btn.setFocusPainted(false);
            btn.setFont(new Font("Segoe UI", Font.BOLD, 14));
            btn.setForeground(Color.WHITE);
            btn.setCursor(new Cursor(Cursor.HAND_CURSOR));

        }

        btnAgregar.setBackground(new Color(0, 180, 120));
        btnActualizar.setBackground(new Color(0, 120, 255));
        btnEliminar.setBackground(new Color(220, 50, 50));

        // POSICIONES

        lblId.setBounds(40, 90, 140, 25);
        txtId.setBounds(220, 90, 200, 30);

        lblFecha.setBounds(40, 150, 140, 25);
        txtFecha.setBounds(220, 150, 200, 30);

        lblTotal.setBounds(40, 210, 140, 25);
        txtTotal.setBounds(220, 210, 200, 30);

        lblMetodo.setBounds(40, 270, 140, 25);
        txtMetodo.setBounds(220, 270, 200, 30);

        lblCliente.setBounds(40, 330, 140, 25);
        txtCliente.setBounds(220, 330, 200, 30);

        lblUsuario.setBounds(40, 390, 140, 25);
        txtUsuario.setBounds(220, 390, 200, 30);

        btnAgregar.setBounds(30, 460, 120, 40);
        btnActualizar.setBounds(180, 460, 120, 40);
        btnEliminar.setBounds(330, 460, 120, 40);

        // AGREGAR COMPONENTES

        add(titulo);

        add(lblId);
        add(txtId);

        add(lblFecha);
        add(txtFecha);

        add(lblTotal);
        add(txtTotal);

        add(lblMetodo);
        add(txtMetodo);

        add(lblCliente);
        add(txtCliente);

        add(lblUsuario);
        add(txtUsuario);

        add(btnAgregar);
        add(btnActualizar);
        add(btnEliminar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FrmVenta formulario = new FrmVenta();
        formulario.setVisible(true);
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmVenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
