/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author hitim
 */
import javax.swing.*;
import java.awt.*;
import Controlador.ControladorCliente;
import Controlador.ControladorProducto;
import Controlador.ControladorVenta;

public class FrmMenu extends javax.swing.JFrame {

    JLabel titulo, lblBienvenida;
    JButton btnClientes, btnProductos, btnVentas, btnSalir;

    public FrmMenu() {
        setTitle("MENÚ PRINCIPAL");
        setSize(600, 500);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLayout(null);
        setResizable(false);

        getContentPane().setBackground(new Color(25, 25, 40));

        titulo = new JLabel("SISTEMA DE GESTIÓN");
        titulo.setBounds(100, 30, 400, 50);
        titulo.setHorizontalAlignment(SwingConstants.CENTER);
        titulo.setFont(new Font("Arial", Font.BOLD, 30));
        titulo.setForeground(new Color(0, 255, 200));
        add(titulo);

        lblBienvenida = new JLabel("¿Qué deseas gestionar hoy?");
        lblBienvenida.setBounds(150, 90, 300, 30);
        lblBienvenida.setHorizontalAlignment(SwingConstants.CENTER);
        lblBienvenida.setFont(new Font("Segoe UI", Font.PLAIN, 16));
        lblBienvenida.setForeground(new Color(200, 200, 200));
        add(lblBienvenida);

        btnClientes  = new JButton("CLIENTES");
        btnProductos = new JButton("PRODUCTOS");
        btnVentas    = new JButton("VENTAS");
        btnSalir     = new JButton("SALIR");

        btnClientes.setBackground(new Color(0, 180, 120));
        btnProductos.setBackground(new Color(0, 120, 255));
        btnVentas.setBackground(new Color(128, 0, 255));
        btnSalir.setBackground(new Color(220, 50, 50));

        JButton[] botones = {btnClientes, btnProductos, btnVentas, btnSalir};
        for (JButton btn : botones) {
            btn.setForeground(Color.WHITE);
            btn.setFocusPainted(false);
            btn.setFont(new Font("Segoe UI", Font.BOLD, 16));
            btn.setCursor(new Cursor(Cursor.HAND_CURSOR));
            btn.setBorderPainted(false);
            add(btn);
        }

        btnClientes.setBounds(175, 150, 250, 55);
        btnProductos.setBounds(175, 220, 250, 55);
        btnVentas.setBounds(175, 290, 250, 55);
        btnSalir.setBounds(175, 380, 250, 45);

        // EVENTOS
        btnClientes.addActionListener(e -> abrirClientes());
        btnProductos.addActionListener(e -> abrirProductos());
        btnVentas.addActionListener(e -> abrirVentas());
        btnSalir.addActionListener(e -> System.exit(0));
    }

    private void abrirClientes() {
        FrmCliente frm = new FrmCliente();
        new ControladorCliente(frm);
        frm.setVisible(true);
        // Opcional: ocultar menú mientras se usa el formulario
        this.setVisible(false);

        // Cuando se cierre el formulario, volver al menú
        frm.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent e) {
                setVisible(true);
            }
        });

        // Cambiar comportamiento del botón X para no cerrar toda la app
        frm.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
    }

    private void abrirProductos() {
        FrmProducto frm = new FrmProducto();
        new ControladorProducto(frm);
        frm.setVisible(true);
        this.setVisible(false);

        frm.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent e) {
                setVisible(true);
            }
        });

        frm.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
    }

    private void abrirVentas() {
        FrmVenta frm = new FrmVenta();
        new ControladorVenta(frm);
        frm.setVisible(true);
        this.setVisible(false);

        frm.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent e) {
                setVisible(true);
            }
        });

        frm.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            new FrmMenu().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
